language: go

services:
  - docker

go:
  - 1.9

before_install:
  - go get -u github.com/Masterminds/glide
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - glide install

script:
  - ./scripts/test.sh
  - gometalinter --fast --vendor --deadline 5m --disable gotype --disable gas --exclude "\.pb.*\.go" --exclude "_strings\.go" --exclude "_test\.go" --exclude "not checked.+Close" ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - '[ "$TRAVIS_BRANCH" == "master"] && ./scripts/build.sh'
  - '[ "$TRAVIS_BRANCH" == "master"] && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"'
  - '[ "$TRAVIS_BRANCH" == "master"] && ./scripts/push.sh'
